---
- name: Test random filter
  hosts: localhost
  gather_facts: False
  vars:
    random_number: "{{ 100 | random }}"
  tasks:
    - name: Print the random number
      debug: var=random_number

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: worker, tags: worker }
    
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: master, tags: master }
