---
- name: pull docker images from master registry
  command: docker image pull tfMaster0:5000/{{ item }}
  with_items:
    - nrd:NRD_11_0_R5
    - nrddb:NRDDB_11_0_R5 
    - collectd:5.8.1-1--NRD_11_0_R5
    - bitnami/mariadb:10.3.15-debian-9-r31
    - prom/mysqld-exporter:v0.10.0 