---
- name: copy pv/pvc yaml file to /tmp
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
    mode: "0755"
  with_items:
    - nrddb-pv.yaml
    - nrddb-pvc.yaml

- name: create kubernetes namespace in k8s
  command: kubectl create namespace nrd-database
  ignore_errors: True
  register: res
  changed_when: "'created' in res.stdout"
  failed_when: "res.rc != 0 and 'already exists' not in res.stderr"

- name: create pv/pvc objects in k8s
  command: kubectl create -f /tmp/{{ item }}
  ignore_errors: True
  with_items:
    - nrddb-pv.yaml
    - nrddb-pvc.yaml
  register: res
  changed_when: "'created' in res.stdout"
  failed_when: "res.rc != 0 and 'already exists' not in res.stderr"