---
- name: Ensure group "nrd" exists
  group:
    name: nrd
    state: present

- name: Add the user 'nrd'
  user:
    name: nrd
    group: nrd

- name: "Create glusterfs /mnt directories"
  file:
      path: "{{ item }}"
      owner: "nrd"
      group: "nrd"
      state: directory
      mode: 0755
  with_items:
    - /mnt/glusterfs/snmp
    - /mnt/glusterfs/kpikci
    - /mnt/glusterfs/cli
    - /mnt/glusterfs/cli/system
    - /mnt/glusterfs/cli/user
    - /mnt/glusterfs/system
    - /mnt/glusterfs/system/user
  become: yes
  become_user: root
  become_method: sudo

- name: "Create a symbolic link"
  file:
      src: "/mnt/glusterfs/snmp"
      dest: "/var/lib/snmp"
      owner: "nrd"
      group: "nrd"
      state: link
  become: yes
  become_user: root
  become_method: sudo

  # with_items:
  #   - /mnt/glusterfs/snmp
  #   - /mnt/glusterfs/kpikci
  #   - /mnt/glusterfs/cli

- name: "Create glusterfs mnt directories"
  file:
      path: "{{ item }}"
      owner: "nrd"
      group: "nrd"
      state: directory
      mode: 0755
  with_items:
    - /var/lib/cli
  become: yes
  become_user: root
  become_method: sudo