---
- name: init tasks on master node
  become: true
  include_tasks: init.yml
  run_once: yes

- name: docker tasks on master node
  include_tasks: docker.yml
  run_once: yes

# - name: helm tasks on master node
#   include_tasks: helm.yml
#   run_once: yes

- name: script tasks on master node
  include_tasks: script.yml
  run_once: yes

- name: db tasks on master node
  include_tasks: db.yml
  run_once: yes

- name: rbac tasks on master node
  include_tasks: rbac.yml
  run_once: yes